[package]

name    = "diagrams"
version = "0.0.0"
authors = [ "Michael White <mwhite85@gmail.com>" ]

[dependencies.image]
git     = "https://github.com/PistonDevelopers/image.git"

[dependencies.freetype-rs]
git     = "https://github.com/PistonDevelopers/freetype-rs.git"

